id: P005474
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:52:29.457361
source_metadata:
  id: bdr:W23741
  title: དག་ཡིག་མཁས་པའི་འབྱུང་གནས
  author: ''
  volumes:
    34dcaf47afc542c9bb8b2574c292b4ce:
      image_group_id: I2562
      title: ''
      volume_number: 1
      total_pages: 435
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
